# Generated by Django 5.2.7 on 2025-10-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_issue_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['issue_number']},
        ),
        migrations.AddField(
            model_name='keypoint',
            name='sentiment',
            field=models.CharField(choices=[('POSITIVE', 'Positif'), ('NEGATIVE', 'Negatif'), ('NEUTRAL', 'Netral')], default='NEUTRAL', max_length=8),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(related_name='issues_tagged', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='keypoint',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('report', 'issue_number')},
        ),
    ]
