# Generated by Django 5.2.7 on 2025-10-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_issue_options_keypoint_sentiment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionIssueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_name', models.CharField(max_length=100)),
                ('issue_1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_summaries', to='api.report')),
            ],
            options={
                'ordering': ['order', 'commission_name'],
                'unique_together': {('report', 'commission_name')},
            },
        ),
    ]
