# Generated by Django 5.2.7 on 2025-10-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commissionissuesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionissuesummary',
            name='issue_1_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commissionissuesummary',
            name='issue_2_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
