# Generated by Django 5.2.7 on 2025-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_commissionissuesummary_issue_1_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoint',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positif'), ('NEGATIVE', 'Negatif'), ('NEUTRAL', 'Netral')], default='NEUTRAL', max_length=8),
        ),
    ]
